name: Deploy on Helios

on:
  push:
    branches:
      - master
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Run gradle jvm client jar task
        run: ./gradlew :jvmClient:jar
      - name: Run gradle jvm server jar task
        run: ./gradlew :jvmServer:jar

      - name: Copy jvmClient.jar via ssh password
        uses: nicklasfrahm/scp-action@main
        with:
          direction: upload
          fingerprint: ${{ secrets.HOST_FINGERPRINT }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: jvmClient/build/libs/jvmClient-1.1-SNAPSHOT.jar
          target: lab5client/jvmClient-1.1-SNAPSHOT.jar

      - name: Copy jvmServer.jar via ssh password
        uses: nicklasfrahm/scp-action@main
        with:
          direction: upload
          fingerprint: ${{ secrets.HOST_FINGERPRINT }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: jvmServer/build/libs/jvmServer-1.1-SNAPSHOT.jar
          target: lab5server/jvmServer-1.1-SNAPSHOT.jar

      - name: Copy jvmClient.jar via ssh password
        uses: nicklasfrahm/scp-action@main
        with:
          direction: upload
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_SASHA }}
          source: jvmClient/build/libs/jvmClient-1.1-SNAPSHOT.jar
          target: lab5client/jvmClient-1.1-SNAPSHOT.jar

      - name: Copy jvmServer.jar via ssh password
        uses: nicklasfrahm/scp-action@main
        with:
          direction: upload
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_SASHA }}
          source: jvmServer/build/libs/jvmServer-1.1-SNAPSHOT.jar
          target: lab5server/jvmServer-1.1-SNAPSHOT.jar
