name: Deploy Jar archives On Helios

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Run gradle jvm client jar task
        run: ./gradlew :jvmClient:jar
      - name: Run gradle jvm server jar task
        run: ./gradlew :jvmServer:jar
