name: Deploy on Helios

on:
  push:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Run gradle jvm client jar task
        run: ./gradlew :jvmClient:jar
      - name: Run gradle jvm server jar task
        run: ./gradlew :jvmServer:jar
      - name: Copy jvmClient.jar via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "./jvmClient/build/libs/*.jar"
          target: "~/lab5client"
      - name: Copy jvmServer.jar via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "jvmServer/build/libs/*.jar"
          target: "~/lab5server"
