name: Deploy Jar archives On Helios

on:
  push:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Run gradle jvm client jar task
        run: ./gradlew :jvmClient:jar
      - name: Run gradle jvm server jar task
        run: ./gradlew :jvmServer:jar
